### ISSUE TITLE
Thoughts about using docsforge with existing readthedocs / sphinx documentation

### ISSUE THREAD

**Issue by mithro** [erez-o/docsforge#49]
I just came across docsforge and the output looks super cool! I was wondering if you had any thoughts or tips about how a project with an existing readthedocs / sphinx setup might be able to get the benefits of docsforge?

An example project would be the Verilog to Routing project who's documentation can be found at https://docs.verilogtorouting.org/en/latest/ and already uses Sphinx + Breathe for some API documentation at places like https://docs.verilogtorouting.org/en/latest/api/vpr/contexts/#classes

Another example would be the Project X-Ray documentation at https://symbiflow.readthedocs.io/projects/prjxray/en/latest/

**Comment by erez-o** [comment]
Thanks for your interest :)

As far as I can see there are 2 main issues for readthedocs/sphinx and breath - project layout and api documentation. 
Both will require a bit of manual conversion, but I think it can be done in a few minutes:

1. **Project and sidebar layout** - instead of sphinx layout, you'll need to convert to docsofrge which is quite similar.

    For example, the layout of https://drogon.docsforge.com/ is:

    ```yaml
    sidebar:
      Basic Tutorial:
      - Getting Started: README.md
      - License: LICENSE
      Wiki:
      - Overview: wiki/ENG-01-Overview.md
      - Installation: wiki/ENG-02-Installation.md
      - Quick Start: wiki/ENG-03-Quick-Start.md
      - Controller Introduction:
        - index: wiki/ENG-04-0-Controller-Introduction.md
        - Controller HttpSimpleController: wiki/ENG-04-1-Controller-HttpSimpleController.md
        - Controller HttpController: wiki/ENG-04-2-Controller-HttpController.md
        - Controller WebSocketController: wiki/ENG-04-3-Controller-WebSocketController.md
      - Filter: wiki/ENG-05-Filter.md
      - View: wiki/ENG-06-View.md
      - Session: wiki/ENG-07-Session.md
      - Database General:
        - index: wiki/ENG-08-0-Database-General.md
        - DataBase DbClient: wiki/ENG-08-1-DataBase-DbClient.md
        - DataBase Transaction: wiki/ENG-08-2-DataBase-Transaction.md
        - DataBase ORM: wiki/ENG-08-3-DataBase-ORM.md
        - DataBase FastDbClient: wiki/ENG-08-4-DataBase-FastDbClient.md
      - Plugins: wiki/ENG-09-Plugins.md
      - Configuration File: wiki/ENG-10-Configuration-File.md
      - Drogon Ctl Command: wiki/ENG-11-drogon_ctl-Command.md
      - AOP Aspect Oriented Programming: wiki/ENG-12-AOP-Aspect-Oriented-Programming.md
      - Benchmarks: wiki/ENG-13-Benchmarks.md
      - Coz profiling: wiki/ENG-14-Coz.md
      - Coroutines: wiki/ENG-16-Coroutines.md
    ```    
    
    ![Screenshot 2021-03-17 133033](https://user-images.githubusercontent.com/4282254/111460771-086f8c80-8725-11eb-938b-3dc3b841236a.png)


2. **API documentation** - docsforge uses doxygen, so anyone coming from breath doesn't have to change anything in the code comments. 

    You need to instruct docsforge which folders/files to scan and extract api from. For example, the API in your example https://docs.verilogtorouting.org/en/latest/api/vpr/contexts/#classes was derived from https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/master/vpr/src/base/vpr_context.h

    To extract any API listed in this file, you need to add the following block to docsforge yaml configuration: 

    ```yaml
    autodocSettings:
      VPR API:
        baseUrl: api-vpr
        language: cpp
        INPUT: vpr/src/base/vpr_context.h
    ```

    Instead of https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/master/doc/src/api/vpr/contexts.rst which requires maintainence if your code changes, the above block does not.

     You can see a simple example API extraction at https://flecs.docsforge.com/master/api-timers/ , or an example that includes custom user groups at https://flecs.docsforge.com/master/api-c/

Hope this helps :)
